### ISSUE TITLE
Feature: User can create patient profiles

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create patient profiles.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user (physical therapist) will be able to open a form, fill in information on the patient, and save the profile to a list of patients.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![user-can-create-patient-profile](https://user-images.githubusercontent.com/96100245/190531165-a293d051-c2ac-4c37-9bbc-d8e4e9a4cbbf.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create data tables for database

### ☁️ Server Tasks

- [x] Update `server/index.js` to get and post values to/from the database
  - [x] Set up preliminaries such as db, app, and middlewares
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render a page with a table for displaying patients
  - [x] Table on mobile only displays patient name and their status
  - [x] Table on desktop displays patient name, a direct icon link to their exercises (to be implemented in a later feature), their status, and an icon to change the status (to be implemented in a later feature)
- [x] Create a component to render a page with a form for a new patient profile
  - [x] 4 text inputs(1 is an email), an integer input, and a textarea
  - [x] submit button that saves information to database
    - [x] also redirects user to Your Patients page after successful POST
  - [x] cancel button that clears the form and navigates user to Your Patients page
- [x] Update component to navigate between the two above created pages
- [x] Create a navbar with an offcanvas menu
  - [x] Patients, New Patients, Exercises, New Exercises

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
