### ISSUE TITLE
Feature: User can update assigned exercises for a patient

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can update assigned exercises for a patient

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the Exercises section of the Patient Profile page, the user (physical therapist) can click the Edit icon in the corner of an exercise to access a small menu. From there, the user can select Edit Assignment to be taken back to the Exercise Assignment page, with the sets and reps value pre-filled with the previously submitted values. The user can make changes to those values and submit the changes to take effect on the patient's exercises list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![10-user-can-update-assigned-exercises](https://user-images.githubusercontent.com/96100245/190718375-fd2ea282-513b-4aa6-b0a8-f7f7fa399821.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle GET and PATCH requests to the patientExercises table in db
  - [x] PATCH requests will take patientExerciseId, sets, reps, and hold
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render page that displays Exercise Assignment and buttons for updating and deleting the assignment.
  - [x] Page displays patient name, exercise name, sets, reps, hold, and exercise description.
  - [x] Update button directs user to the Assign Exercise page
    - [x] Previously submitted values will be prefilled in the inputs
    - [x] Heading and Submit buttons will have altered text to reflect updating the assignment instead of creating a new assignment.
- [x] Update Assign Exercise component to send PATCH request when the submission is an update to an exercise assignment.

### 🧑‍⚕️ Clean Up Tasks

- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
