### ISSUE TITLE
Feature: User can remove assigned exercises from a patient

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove assigned exercises from a patient

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the exercises section of the Patient Profile page, the user can click the Edit icon in the corner of an exercise to open a small menu. From this menu, the user can select Remove to trigger an action to remove the selected exercise from the patient's exercise list. Upon confirmation of removal, the exercise is taken off the patient's exercise list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![11-user-can-remove-an-assigned-exercise](https://user-images.githubusercontent.com/96100245/190718945-ccb003bf-d10a-4fdc-8cb1-d32190e04159.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle DELETE requests on the patientExercises table in db
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Exercise Assignment component to create Delete button and provide functionality
  - [x] First click on Delete button opens modal for confirmation of delete request
  - [x] Once modal is open, Cancel and Confirm Delete buttons are available
    - [x] Cancel closes the modal
    - [x] Confirm Delete calls a function that sends a DELETE request to the server
      - [x] Once delete is successful, user is returned to the Patient Profile

### 🧑‍⚕️ Clean Up Tasks

- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
