### ISSUE TITLE
Feature: User can review assigned exercises

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can review assigned exercises

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user (patient) can view the exercises that have been assigned to them from their physical therapist. This view is on the My Exercises page. The user can also keep track of which exercises have been completed by using the checkboxes to the left of each exercise card. More details on the exercise can be viewed when the user clicks the Information icon in the top right corner of the exercise card.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![12-user-can-view-assigned-exercises](https://user-images.githubusercontent.com/96100245/190720616-1b8b6d74-d2fa-4cd5-987a-14c43b85bda1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update sign-in POST handler in `server/index.js` to retrieve accountType of user upon sign-in
- [x] Remove userId validation from handlers that have patientId and/or exerciseId validation
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update auth component to contain a temporary dropdown in the sign-up form
  - [x] Dropdown allows new user to select therapist or patient for the accountType
- [x] Update app.jsx component to sort patient and therapist users in renderPage to keep from crossing over
  - [x] sign-in and sign-up routes will remain untouched
  - [x] if statement that checks accountType of user to determine which pages can be accessed
- [x] Create a component to render a home page for patients upon sign-in
  - [x] This page will display a list of exercises that have been assigned to the patient by their physical therapist
    - [x] Each card in the list will show the name of the exercise as well as the sets/reps/hold for the exercise
    - [x] Clicking on the exercise card will show the exercise profile (name, S/R/H, and description)

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
