### ISSUE TITLE
Feature: User can create, edit, and update feedback on assigned exercises

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create feedback on assigned exercises

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user (patient) can write feedback within an input on the Exercise Profile page. This page is accessed when the Information icon is clicked on the exercise cards in the My Exercises page. The user can then save the feedback to the exercise, to be viewed by the physical therapist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![13-user-can-create-feedback-on-exercise](https://user-images.githubusercontent.com/96100245/190721669-69d213ed-339e-498c-934e-7308365c9aa9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update PATCH handler for patientExercises in `server/index.js` to receive and post feedback from the patient user
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Exercise Details component to handle submission of feedback on exercises
  - [x] Add a form to the exercise card that takes feedback on the given exercise
    - [x] Clear and Save Feedback buttons for clearing or submission of the form, respectively
  - [x] Use a PATCH request to save the feedback to the patientExercise that the therapist created

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
