### ISSUE TITLE
Feature: User can review feedback from a patient

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can review feedback from a patient

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user (physical therapist) can review feedback that was left by a patient. This can be done by clicking the Edit icon in the corner of an exercise card on the Patient Profile's exercises list. A small menu will pop up, and the user can select the option for Review Feedback. When selected, a small pop-up will appear on the screen with the patient's feedback text inside.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![15-user-can-review-patient-feedback](https://user-images.githubusercontent.com/96100245/190728059-f41a75b5-798a-44e8-93cc-de65ee3fa17d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to add accountType to the users table

### ☁️ Server Tasks

- [ ] Update `server/index.js` to use sgMail API
  - [ ] Create handler for emails sent for patient sign-up
  - [ ] Create handler for emails sent for Forgot Password
  - [ ] Create handler for getting user information by email
  - [ ] Create handler for updating user passwords (PATCH)
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
