### ISSUE TITLE
Feature: User can create exercises

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create exercises.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user (physical therapist) will be able to open a form, fill in information on a new exercise, and submit the new exercise to a collection of exercises.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![2-user-can-create-exercise](https://user-images.githubusercontent.com/96100245/190531998-edfba2d5-2326-4910-9713-446f212c8795.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to POST exercise submissions to the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render a form for receiving New Exercise information
  - [x] In the component, check for exercises that already have the same name as the current input
  - [x] Cancel button routes user back to Your Patients page
  - [x] On submit, the input information is POSTed to the database
    - [x] The user is routed to the Your Exercises page upon successful submission (in fetch)
- [x] Create a fetch request for posting the exercise data to the database
  - [x] Include the location.hash route change to facilitate the navigation of the user upon submission
- [x] Create a component to render cards for each submitted exercise on the Your Exercises page
  - [x] Create a Dropdown button with each of the different classes of exercises listed
    - [x] Clicking one of the Dropdown options changes state for the current targetArea
    - [x] The current targetArea state will alter the Exercise page subheader, and filter for the exercises in that targetArea

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
