### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#27]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account with an email and a password.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to create an account with an email and a password. Being logged in to the account will allow the user to see any patients and exercises that they've created profiles for. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to add userId to each table so that different users will see different information.

### ☁️ Server Tasks

- [x] Update `server/index.js` to POST new user information to the db
  - [x] User information will contain an email and a hashedPassword
- [x] Update `server/index.js` to POST user information and compare to the db user information
  - [x] User information will contain an email and a hashedPassword
  - [x] If there is a match, payload and token are sent back.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render a sign-in and sign-up page
- [x] Update app.jsx with functions and variable for AppContext
  - [x] handleSignIn and handleSignUp to be called in auth.jsx
  - [x] variables in state to keep track of user information, json web token, and isAuthorizing status
  - [x] store jwt in local storage to keep user logged in
- [x] Create a form component to receive email and password
  - [x] Call form component in auth.jsx to allow user to sign in or sign up for an account

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
