### ISSUE TITLE
Feature: User can review patient profiles

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can review patient profiles.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user (physical therapist) will be able to click on a name in the Your Patients page to show the respective patient's profile. The profile will display all the information that was submitted when the patient profile was created. There will be a button that the user can click to open the Exercises display for the selected patient, which will contain all the exercises that have been assigned to the patient. There will be buttons in the Patient Profile as well as the Exercises display that can navigate the user back to the Your Patients page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![3-user-can-review-patient-profiles](https://user-images.githubusercontent.com/96100245/190532595-bc8e7bec-1495-4246-aa44-c528aead9a23.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to GET patient information by patient id from the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Your Patients component with links on patient names to navigate to Patient Profile
  - [x] Links direct via hash route to patientId
- [x] Create a component to render page that displays the patient info/assigned exercises (later feature)
  - [x] Component renders a card that contains the patient information (name, age, injuryAilment)
    - [x] Patient information comes from fetch request with patientId
  - [x] Render cards for each exercise assigned (use placeholder exercises for now)
    - [x] Add in reps/sets information
  - [x] Link/button at the top of the page to redirect user back to Your Patients page

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
