### ISSUE TITLE
Feature: User can review exercises

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can review exercises

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user (physical therapist) will be able to click on an exercise on the Your Exercises page to open up the Exercise Profile page. The Exercise Profile page will display all the information that was submitted when the exercise was created. The Exercise Profile page will also have a button to navigate the user back to the Your Exercises page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![4-user-can-review-exercises](https://user-images.githubusercontent.com/96100245/190533442-60a0e7b4-d84f-4e42-82c9-60b4296b5c33.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to GET exercise information by exercise id from the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Your Exercises component with links on exercise cards to navigate to Exercise Profile
  - [x] Links direct via hash route to exerciseId
- [x] Create a component to render page that displays exercise information for a clicked exercise
  - [x] Component renders a card that contains the exercise information (name, targetArea, description)
    - [x] Exercise information is pulled with fetch request with exerciseId
    - [x] Button at bottom of card for assigning the exercise to a patient (unlinked for now)
  - [x] Link/button at top of page to redirect user back to Your Exercises page

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
