### ISSUE TITLE
Feature: User can update patient profile

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can update patient profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the Patient Profile page, the user (physical therapist) will be able to navigate to the Edit Patient Profile page. On this page, the user will be able to update any of the information that had been submitted when the profile was created. Additionally, the user will be able to note whether the patient is still actively visiting the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![5-user-can-update-patient-profile](https://user-images.githubusercontent.com/96100245/190533921-3eca09d4-c7cc-434d-93e1-9299dc3948d9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle PATCH requests for patients
  - [x] PATCH requests will take (firstName, lastName, email, age, injuryAilment, notes, and isActive)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Patient Profile component to render an edit icon with a patientId href
  - [x] Directs the user to New Patient page with some changes
    - [x] Header is changed to Edit Patient Profile if certain conditions are met
    - [x] Inputs are filled in with patient information from GET patientId request
    - [x] Check if inputs are cleared upon exit
    - [x] Create switch for changing the isActive status
      - [x] Switch only appears in Edit Patient, not in New Patient
  - [x] Update handleSubmit to check for New / Updated Patient onSubmit
    - [x] After submission, user is directed back to Patient Profile to see updated information

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
