### ISSUE TITLE
Feature: User can update exercises

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can update exercises

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user (physical therapist) will be able to navigate to the Edit Exercise page from the Exercise Profile. They will be able to change any of the information that was provided when the exercise was created.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![6-user-can-update-exercise](https://user-images.githubusercontent.com/96100245/190572385-2423ba21-b046-4a8b-a3bc-84bcb3c30025.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle PATCH requests for exercises
  - [x] PATCH requests will take (name, targetArea, and description)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Exercise Profile component to render an edit icon with a modal, prompting for Edit Exercise
  - [x] Directs the user to New Exercise page with some changes
    - [x] Header is changed to Edit Exercise Profile if certain conditions are met
    - [x] Inputs are filled in with exercise information from GET exerciseId request
    - [x] Check if inputs are cleared upon exit
- [x] Update handleSubmit to check for New / Updated Exercise onSubmit
  - [x] After submission, user is directed back to Exercise Profile to see updated information

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
