### ISSUE TITLE
Feature: User can delete an exercise

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an exercise

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the Exercise Profile, the user (physical therapist) will be able to click the Edit icon prompting for changes to the exercise. On the prompt, the user can select to delete the exercise. Upon confirmation, the exercise is deleted from the user's exercise list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![8-user-can-delete-an-exercise](https://user-images.githubusercontent.com/96100245/190573342-0e9b842b-4185-4d44-8957-3ddb9ab83b1a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle DELETE requests for exercises
  - [x] DELETE requests will take exerciseId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Exercise Profile component to switch modals when Delete Exercise is selected (from within Edit modal)
  - [x] Create new modal that will prompt for confirmation of Delete request
    - [x] Cancel button directs user back to Edit modal
    - [x] Confirm Delete button initiates deleteExercise method
  - [x] Create method deleteExercise with fetch request type: DELETE
    - [x] Upon successful completion of delete request, user is redirected to Your Exercise page

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
