### ISSUE TITLE
Feature: User can assign an exercise to a patient

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can assign an exercise to a patient

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user (physical therapist) can select a patient from the Your Patients page. From the selected patient's Patient Profile page, the user can navigate to the patient's exercise list. On this page, clicking Add Exercise will navigate the user to the Your Exercises page to select which exercise will be added to the patient. When an exercise is selected, the Exercise Assignment page will open, where the user can fill in the sets and reps for the exercise. Clicking Assign Exercise will add the exercise to the patient's exercise list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![9-user-can-assign-exercises-to-patient](https://user-images.githubusercontent.com/96100245/190574504-92fc0c2c-66f2-44d1-be8f-621cf17eb5a9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to POST exercise assignments to the patientExercise table
  - [x] POST request should contain patientId, exerciseId, reps, sets, and feedback(empty string for now)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to select exercises that will be assigned to the patient
  - [x] Navigation to this component page from Patient Profile
  - [x] Incorporate Exercise Cards to list available exercises for selection
    - [x] Only display the exercises that have not already been assigned to the patient
    - [x] When an exercise is selected, the user is directed to the next page
      - [x] The patientId and exerciseId are carried over to the next page within the URL
- [x] Update Exercise Profile to be able to assign the exercise to a patient
  - [x] Clicking Assign Exercise opens a dropdown that displays the patient names
    - [x] Only patients who have not been assigned the exercise will have their names displayed in the dropdown
    - [x] Clicking on a name in the dropdown directs the user to Assign Exercise to proceed with exercise assignment as normal
- [x] Create component to render a form for inputting reps and sets for the selected exercise
    - [x] On this page, the selected exercise will display along with prompts for reps/sets for the exercise.
    - [x] Once complete, the user will click Assign Exercise to submit the form
      - [x] onSubmit, use a fetch request to send POST to the server
- [x] Update Patient Profile component to render patientExercises instead of exercises
  - [x] Use GET request on patientExercises table in db to pull all exercises selected by patientId
  - [x] If no exercises are assigned yet, display message

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
